### ISSUE TITLE
assert for too many shards

### ISSUE THREAD

**Issue by burdges** [paritytech/rs-ec-perf#20]
We need an assert that prevents dong too many shards: https://github.com/paritytech/polkadot/pull/6308#discussion_r1027865227

**Comment by ordian** [comment]
We already have it https://github.com/paritytech/polkadot/pull/6308#discussion_r1027961443
Btw, the dependency we're using in in polkadot was published from https://github.com/paritytech/reed-solomon-novelpoly/.

**Comment by burdges** [comment]
Yeah I was just being stupid..  lol

**Comment by burdges** [comment]
I know it lives elsewhere, this is the fork where we envision eventually optimizing the arithmetic, but everyone is busy with other stuff.
